(function(g){var window=this;var BDa=function(a,b){return g.ec(a,b)},a6=function(a){g.mn(a,"zx",g.Eb());
return a},b6=function(a,b,c){g.Ea(c)||(c=[String(c)]);
g.pn(a.o,b,c)},CDa=function(a,b){var c=[];
g.Xk(b,function(a){try{var b=g.MD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.ya(b)?g.LD(b)&&c.push(a):c.push(a)},a);
return c},DDa=function(a,b){var c=CDa(a,b);
(0,g.E)(c,function(a){g.MD.prototype.remove.call(this,a)},a)},EDa=function(a){if(a.Xd){if(a.Xd.locationOverrideToken)return{locationOverrideToken:a.Xd.locationOverrideToken};
if(null!=a.Xd.latitudeE7&&null!=a.Xd.longitudeE7)return{latitudeE7:a.Xd.latitudeE7,longitudeE7:a.Xd.longitudeE7}}return null},FDa=function(a,b,c,d){var e=new g.cn(null,void 0);
a&&g.dn(e,a);b&&g.en(e,b);c&&g.fn(e,c);d&&g.gn(e,d);return e},GDa=function(a){return a?a.dataset?a.dataset[g.CF("loaded")]:a.getAttribute("data-loaded"):null},c6=function(a,b){g.vG[a]=!0;
var c=g.tG();c&&c.publish.apply(c,arguments);g.vG[a]=!1},HDa=function(a){g.wG[a]&&(a=g.wG[a],(0,g.E)(a,function(a){g.uG[a]&&delete g.uG[a]}),a.length=0)},IDa=function(a){var b=g.tG();
if(b)if(b.clear(a),a)HDa(a);else for(var c in g.wG)HDa(c)},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Xm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",JDa(this,a.capabilities||""),KDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},JDa=function(a,b){a.capabilities.clear();
(0,g.fe)(b.split(","),g.La(BDa,LDa)).forEach(function(b){a.capabilities.add(b)})},KDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},MDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},NDa=function(a){return new e6(a)},ODa=function(a){return g.Ea(a)?(0,g.J)(a,NDa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ea(a)?"["+(0,g.J)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},PDa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},j6=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},k6=function(a,b){return g.Ra(a,function(a){return f6(a,b)})},QDa=function(){var a=(0,g.EH)();
a&&DDa(a,a.o.ke(!0))},l6=function(){var a=g.HH("yt-remote-connected-devices")||[];
g.ob(a);return a},RDa=function(a){if(g.Va(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},SDa=function(a){g.GH("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.HH("yt-remote-device-id");a||(a=i6(),g.GH("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.C(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.C(a,b);g.JH()&&g.qb(a,b);a=RDa(a);if(g.Va(a))try{g.cH("remote_sid")}catch(c){}else try{g.bH("remote_sid",a.join(","),-1)}catch(c){}},TDa=function(){return g.HH("yt-remote-session-browser-channel")},UDa=function(){return g.HH("yt-remote-local-screens")||[]},VDa=function(){g.GH("yt-remote-lounge-token-expiration",!0,86400)},WDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(UDa(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Lm)(c,function(a){return!g.C(b,a)})&&VDa();
g.GH("yt-remote-local-screens",a,31536E3)},XDa=function(a,b){g.GH("yt-remote-session-browser-channel",a);
g.GH("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.C(c,d)||c.push(d);SDa(c);o6()},p6=function(a){a||(g.IH("yt-remote-session-screen-id"),g.IH("yt-remote-session-video-id"));
o6();a=l6();g.Za(a,n6());SDa(a)},YDa=function(){if(!q6){var a=g.XD();
a&&(q6=new g.GD(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},ZDa=function(){var a=window.document.createElement("a");
g.sd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ib(a)},$Da=function(a,b,c){c=void 0===c?null:c;
var d=g.Zd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.wd(d,g.ve("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},aEa=function(a){a=void 0===a?null:a;
var b=ZDa(),c=window.document.getElementById(b),d=c&&GDa(c);d||c&&!d||(c=$Da(b,function(){GDa(c)||(g.DF(c,"loaded","true"),g.AG(b),g.CE(g.La(IDa,b),0))},a))},bEa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):aEa(a)},r6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},cEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?dEa(a.shift(),function(){s6(a)}):t6()},eEa=function(a){return"chrome-extension://"+a+u6},dEa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},v6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},t6=function(){var a=cEa();
a&&a(!1,"No cast extension found")},w6=function(){if(fEa){var a=2,b=cEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;dEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},gEa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(w6(),a({command:"cast.sender.init"}))},hEa=function(){w6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+u6,"//www.gstatic.com/eureka/clank"+u6])},x6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Pd=b;this.D=(0,g.A)(this.ML,this);this.o=!1;this.A=0;this.B=this.Ha=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.tn(this);this.A=new g.Ig;this.A.setInterval(250)},jEa=function(a,b,c){a.kk=1;
a.Oh=a6(b.clone());a.zj=c;a.D=!0;iEa(a,null)},A6=function(a,b,c,d,e){a.kk=1;
a.Oh=a6(b.clone());a.zj=null;a.D=c;e&&(a.uG=!1);iEa(a,d)},iEa=function(a,b){a.jl=(0,g.I)();
B6(a);a.si=a.Oh.clone();b6(a.si,"t",a.F);a.qo=0;a.Zc=a.o.Zt(a.o.ho()?b:null);0<a.Gu&&(a.wr=new g.Fl((0,g.A)(a.GH,a,a.Zc),a.Gu));a.Y.W(a.Zc,"readystatechange",a.IW);var c=a.Zi?g.mc(a.Zi):{};a.zj?(a.ys="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Zc.send(a.si,a.ys,a.zj,c)):(a.ys="GET",a.uG&&!g.Ud&&(c.Connection="close"),a.Zc.send(a.si,a.ys,null,c));a.o.Nf(1)},mEa=function(a,b,c){for(var d=!0;!a.Ji&&a.qo<c.length;){var e=kEa(a,c);
if(e==C6){4==b&&(a.Ph=4,D6(15),d=!1);break}else if(e==lEa){a.Ph=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Ph=1,D6(17),d=!1);a.Uf=a.Uf&&d;d||(F6(a),G6(a))},kEa=function(a,b){var c=a.qo,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return lEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.qo=d+c;return e},oEa=function(a,b){a.jl=(0,g.I)();
B6(a);var c=b?window.location.hostname:"";a.si=a.Oh.clone();g.mn(a.si,"DOMAIN",c);g.mn(a.si,"t",a.F);try{a.Vf=new window.ActiveXObject("htmlfile")}catch(n){F6(a);a.Ph=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in nEa)k=H6[l]=nEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.xd(g.Lc("b/12014412"),d+"</body></html>");a.Vf.open();a.Vf.write(g.ld(c));a.Vf.close();a.Vf.parentWindow.m=(0,g.A)(a.QV,a);a.Vf.parentWindow.d=(0,g.A)(a.DF,a,!0);a.Vf.parentWindow.rpcClose=(0,g.A)(a.DF,a,!1);c=a.Vf.createElement("DIV");a.Vf.parentWindow.document.body.appendChild(c);d=g.Zc(a.si.toString());d=g.yb(g.Wc(d));d=g.xd(g.Lc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.rd(c,g.ld(d));a.o.Nf(1)},
B6=function(a){a.Iy=(0,g.I)()+a.C;
pEa(a,a.C)},pEa=function(a,b){if(null!=a.Fl)throw Error("WatchDog timer not null");
a.Fl=I6((0,g.A)(a.fW,a),b)},J6=function(a){a.Fl&&(g.v.clearTimeout(a.Fl),a.Fl=null)},G6=function(a){a.o.cC()||a.Ji||a.o.ar(a)},F6=function(a){J6(a);
g.uf(a.wr);a.wr=null;a.A.stop();g.zn(a.Y);if(a.Zc){var b=a.Zc;a.Zc=null;b.abort();b.dispose()}a.Vf&&(a.Vf=null)},E6=function(a,b){try{a.o.wF(a,b),a.o.Nf(4)}catch(c){}},rEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;qEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){rEa(a,b,c,d,f)},f)})}},qEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},sEa=function(a){this.o=a;
this.A=new y6},tEa=function(a){var b=L6(a.o,a.Vl,"/mail/images/cleardot.gif");
a6(b);rEa(b.toString(),5E3,(0,g.A)(a.OK,a),3,2E3);a.Nf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Pe=new z6(a,void 0,void 0,void 0),a.Pe.Zi=a.Eu,b=a.o,b=L6(b,b.ho()?a.Nm:null,a.Fu),D6(5),!g.Sd||g.Dc(10))b6(b,"TYPE","xmlhttp"),A6(a.Pe,b,!1,a.Nm,!1);else{b6(b,"TYPE","html");var c=a.Pe;a=!!a.Nm;c.kk=3;c.Oh=a6(b.clone());oEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},uEa=function(a,b){this.o=a;
this.map=b;this.context=null},vEa=function(a){g.wf.call(this,"statevent",a)},wEa=function(a,b){g.wf.call(this,"timingevent",a);
this.size=b},xEa=function(a){g.wf.call(this,"serverreachability",a)},AEa=function(a){yEa(a);
if(3==a.o){var b=a.Nn++,c=a.Ap.clone();g.mn(c,"SID",a.B);g.mn(c,"RID",b);g.mn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.kk=2;b.Oh=a6(c.clone());(new window.Image).src=b.Oh;b.jl=(0,g.I)();B6(b)}zEa(a)},BEa=function(a){a.kL(1,0);
a.Ap=L6(a,null,a.Du);Q6(a)},yEa=function(a){a.Ah&&(a.Ah.abort(),a.Ah=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Mg&&(g.v.clearTimeout(a.Mg),a.Mg=null);R6(a);a.se&&(a.se.cancel(),a.se=null);a.Ih&&(g.v.clearTimeout(a.Ih),a.Ih=null)},CEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new uEa(a.ER++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.se||a.Ih||(a.Ih=I6((0,g.A)(a.CF,a),0),a.ck=0)},EEa=function(a,b){if(1==a.o){if(!b){a.Nn=Math.floor(1E5*Math.random());
var c=a.Nn++,d=new z6(a,"",c,void 0);d.Zi=null;var e=S6(a),f=a.Ap.clone();g.mn(f,"RID",c);g.mn(f,"CVER","1");P6(a,f);jEa(d,f,e);a.se=d;a.o=2}}else 3==a.o&&(b?DEa(a,b):0==a.A.length||a.se||DEa(a))},DEa=function(a,b){if(b)if(6<a.Mi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Nn-1;var d=S6(a)}else c=b.G,d=b.zj;else c=a.Nn++,d=S6(a);var e=a.Ap.clone();g.mn(e,"SID",a.B);g.mn(e,"RID",c);g.mn(e,"AID",a.Fk);P6(a,e);c=new z6(a,a.B,c,a.ck+1);c.Zi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.se=c;jEa(c,e,d)},P6=function(a,b){if(a.Od){var c=a.Od.IB();
c&&g.Rb(c,function(a,c){g.mn(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Mi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Mi?e:f-d;try{g.Rb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},FEa=function(a){a.Ec||a.Mg||(a.G=1,a.Mg=I6((0,g.A)(a.BF,a),0),a.Tj=0)},T6=function(a){if(a.Ec||a.Mg||3<=a.Tj)return!1;
a.G++;a.Mg=I6((0,g.A)(a.BF,a),GEa(a,a.Tj));a.Tj++;return!0},M6=function(a,b,c){a.us=c;
a.ig=b.Yg;a.F||BEa(a)},R6=function(a){null!=a.Oi&&(g.v.clearTimeout(a.Oi),a.Oi=null)},GEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Od&&(c=null);var d=(0,g.A)(a.yX,a);c||(c=new g.cn("//www.google.com/images/cleardot.gif"),a6(c));qEa(c.toString(),1E4,d)}else D6(2);HEa(a,b)},HEa=function(a,b){a.o=0;
a.Od&&a.Od.HA(b);zEa(a);yEa(a)},zEa=function(a){a.o=0;
a.ig=-1;if(a.Od)if(0==a.C.length&&0==a.A.length)a.Od.Lt();else{g.cb(a.C);var b=g.cb(a.A);a.C.length=0;a.A.length=0;a.Od.Lt(b)}},L6=function(a,b,c){var d=g.nn(c);
if(""!=d.A)b&&g.en(d,b+"."+d.A),g.fn(d,d.D);else{var e=window.location;d=FDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.qm&&g.Rb(a.qm,function(a,b){g.mn(d,b,a)});
g.mn(d,"VER",a.Mi);P6(a,d);return d},I6=function(a,b){if(!g.Ga(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new vEa(V6,a))},IEa=function(){},JEa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.L.call(this);
this.o=new g.V(this.GV,0,this);g.M(this,this.o);this.Pd=5E3;this.A=0;if(g.Ga(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ga(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.L=a;
this.F=b;this.B=new g.FD;this.A=new W6(this.bY,this);this.o=this.kb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},KEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.us,sessionId:a.o.B,arrayId:a.o.Fk}},LEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&EEa(a.o),AEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},MEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Wg(a)||"";a=g.Pb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.ya(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.fh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Td:g.La(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.TE(b,a)},QEa=function(){var a=NEa;
OEa();b7.push(a);PEa(b7)},c7=function(a,b){OEa();
var c=b7,d=REa(a,String(b));g.Va(c)?SEa(d):(PEa(c),(0,g.E)(c,function(a){a(d)}))},OEa=function(){b7||(b7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ba("yt.mdx.remote.debug.handlers_",b7,void 0))},SEa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},PEa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.E)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},REa=function(a,b){var c=((0,g.I)()-TEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.kG.call(this);
this.G=a;this.o=[]},UEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},VEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.fe)(a.o,function(a){return!!j6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=UEa(a,b[d])||c;return c},WEa=function(a,b){var c=a.o.length;
a.o=(0,g.fe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.kG.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ha=window.NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;i7(this);this.info("Initializing with "+h6(this.o))},XEa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.aM,a),(0,g.A)(a.ZL,a))}},i7=function(a){var b=ODa(UDa());
b=(0,g.fe)(b,function(a){return!a.uuid});
return VEa(a,b)},k7=function(a,b){WDa((0,g.J)(a.o,MDa));
b&&VDa()},m7=function(a,b){g.kG.call(this);
this.F=b;var c=g.HH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.C(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;l7("Initialized with "+g.Og(this.o))},YEa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Wb(b)!=g.Wb(a.o))var c=!1;
else{c=g.bc(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Og(a.o)),a.o=b,a.U("screenChange"));ZEa(a)},o7=function(a){(0,window.isNaN)(a.B)||g.EE(a.B);
a.B=g.CE((0,g.A)(a.Fx,a),0<a.C&&a.C<(0,g.I)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},$Ea=function(a){var b={};
(0,g.E)(a.F(),function(a){a.token?b[a.token]=a.id:this.xc("Requesting availability of screen w/o lounge token.")});
return b},ZEa=function(a){a=g.bc(g.Sb(a.o,function(a){return a}));
g.ob(a);a.length?g.GH("yt-remote-online-screen-ids",a.join(","),60):g.IH("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};aFa(this)},cFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Je();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=q7(a,k);YEa(a.A,l,function(a){e(a?l:null)})}else c?bFa(a,c,(0,g.A)(function(a){var f=q7(this,new e6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));YEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},dFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},bFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.TE($6(a.F,"/pairing/get_lounge_token_batch"),e)},eFa=function(a){a.o=a.B.Je();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},aFa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.nM,a));eFa(a);a.C=ODa(g.HH("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+h6(a.C));a.A=new m7(a.F,(0,g.A)(a.Je,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.GH("yt-remote-automatic-screen-cache",(0,g.J)(a.C,MDa)));r7(a);a.D[b.uuid]=b.id;g.GH("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.HH("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.kG.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.hY,this);this.D=(0,g.A)(this.rW,this);this.C=g.CE((0,g.A)(function(){fFa(this,null)},this),12E4)},gFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Og(b))},fFa=function(a,b){g.EE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.dr,a),d=(0,g.A)(a.Oe,a);a.SB(b,c,d,5)}}else a.Oe(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.y;this.F=window.NaN;this.L=(0,g.A)(this.kY,this);this.o=g.y},hFa=function(a){a.o=a.J.MH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.y;
this.dr(a)},a),(0,g.A)(function(a){this.o=g.y;
this.Oe(a)},a))},iFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}YDa()&&(b.env_useStageMdx=1);return g.dh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.CE((0,g.A)(this.Hk,this,null),150)},x7=function(a,b,c,d){g.kG.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.SU,this)},jFa=function(a,b){return b?g.Ra(a.B,function(a){return f6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},NEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.uf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.zF,a,b)),b.B?a.U("yt-remote-cast2-session-change",b.B):c&&a.o.Hk(null)):a.U("yt-remote-cast2-session-change",null))},kFa=function(a){var b=a.A.LH(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(a){c&&f6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=jFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},qFa=function(a,b,c,d,e,f,k){lFa()?mFa(b,e,f,k)&&(C7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?nFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?nFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.IH("yt-remote-cast-available"),g.IH("yt-remote-cast-receiver"),oFa(),
c(!1))},d?bEa():v6("CriOS")?gEa():v6("Android")&&v6("Chrome/")&&window.navigator.presentation?hEa():window.chrome&&window.navigator.presentation&&!v6("Edge")?(w6(),s6(pFa.map(eEa))):t6())):B7("Cannot initialize because not running Chrome")},oFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ba("yt.mdx.remote.cloudview.instance_",null,void 0);rFa(!1);g.yG(G7);G7.length=0},H7=function(){return!!g.HH("yt-remote-cast-installed")},sFa=function(){var a=g.HH("yt-remote-cast-receiver");
return a?a.friendlyName:null},tFa=function(){B7("clearCurrentReceiver");
g.IH("yt-remote-cast-receiver")},uFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.xG("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},lFa=function(){var a=0<=g.Pb.search(/ (CrMo|Chrome|CriOS)\//);
return g.dL||a},vFa=function(a,b){F7().init(a,b)},mFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.GH("yt-remote-cast-available",a);c6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.GH("yt-remote-cast-receiver",a);c6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.GH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+g6(a));
a||g.IH("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",a)}),g.Ba("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},nFa=function(a,b){E7(!0);
C7(!1);vFa(a,function(a){a?(rFa(!0),g.AG("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.IH("yt-remote-cast-available"),g.IH("yt-remote-cast-receiver"),oFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.GH("yt-remote-cast-installed",a)},I7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},rFa=function(a){B7("setApiReady_ "+a);
g.Ba("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ba("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.mg=!1;this.J=this.H=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.mg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.I)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=window.NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.I)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.I)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.nc(a.o);b.hasPrevious=a.mg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.kG.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.WC;this.B=this.A=null;this.J=(0,g.A)(this.oS,this);this.G=(0,g.A)(this.Qn,this);this.H=(0,g.A)(this.nS,this);this.K=(0,g.A)(this.AS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bz,this),wFa(this))):c=3;0!=c&&(b?this.bz(c):g.CE((0,g.A)(function(){this.bz(c)},this),0));
var d=uFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},wFa=function(a){(0,g.E)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.NU,a),this))},a)},xFa=function(a){(0,g.E)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Pc()&&g.YC(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){xFa(a);
a.C.setPlayerContextData(R7(b));wFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Qn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Qn(a.B.media[0]))},yFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.xc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.xc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.kG.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.V=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.V.push(g.UF(window,"beforeunload",(0,g.A)(this.QL,this)));this.A=[];this.qb=new L7;this.ba=b.id;this.o=zFa(this,c);this.o.subscribe("handlerOpened",this.sS,this);this.o.subscribe("handlerClosed",this.pS,this);this.o.subscribe("handlerError",this.qS,this);this.o.subscribe("handlerMessage",this.rS,this);MEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.qb.videoId;g.JH()&&g.GH("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},zFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},AFa=function(a){a.D=g.CE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.EE(a.D);
a.D=window.NaN},d8=function(a){g.EE(a.M);
a.M=window.NaN},BFa=function(a){e8(a);
a.L=g.CE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.EE(a.L);
a.L=window.NaN},DFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&(0,window.isNaN)(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),CFa(a)):a.F(1)},EFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.hc(b.params)?a.qb.o=null:a.qb.o=b.params,a.U("remotePlayerChange"))},FFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.U("remoteQueueChange")},HFa=function(a,b){b.params=b.params||{};
FFa(a,b);GFa(a,b);a.U("autoplayDismissed")},GFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
O7(a.qb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.qb.H=(0,window.isNaN)(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:
e;1==a.qb.playerState?BFa(a):e8(a);a.U("remotePlayerChange")},IFa=function(a,b){if(-1E3!=a.qb.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);O7(a.qb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},JFa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=(0,window.parseInt)(b.params.volume,10);a.qb.muted=c;a.U("remotePlayerChange")},KFa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},LFa=function(a,b){var c="true"==b.params.hasNext;
a.qb.mg="true"==b.params.hasPrevious;a.qb.hasNext=c;a.U("previousNextChange")},CFa=function(a){g.EE(a.K);
a.K=g.CE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Og(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.xd=a;this.A=[];this.A.push(this.xd.$_s("screenChange",(0,g.A)(this.fY,this)));this.A.push(this.xd.$_s("onlineScreenChange",(0,g.A)(this.mU,this)))},QFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.rE("MDX_CONFIG")||b;QDa();o6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),YDa()&&(h8.o="/api/loungedev"));i8||(i8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ba("yt.mdx.remote.deferredProxies_",i8,void 0));MFa();var c=j8();if(!c){var d=new p7(h8);g.Ba("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);qFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ba("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Og(b)),m8.push(g.xG("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),m8.push(g.xG("yt-remote-cast2-receiver-selected",function(){n8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.xG("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.xG("yt-remote-cast2-session-change",NFa)),m8.push(g.xG("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),tFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.zE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Og(a)),OFa(a),c.start(),k8()||PFa())},SFa=function(){var a=RFa();
H7()&&g.HH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},RFa=function(){var a=j8().xd.$_gos();
var b=q8();b&&r8()&&(j6(a,b)||a.push(b));return PDa(a)},s8=function(){var a=TFa();
!a&&H7()&&sFa()&&(a={key:"cast-selector-receiver",name:sFa()});return a},TFa=function(){var a=RFa(),b=q8();
b||(b=o8());return g.Ra(a,function(a){return b&&f6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().Je();return k6(b,a)},NFa=function(a){l8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.w("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.w("yt.mdx.remote.currentScreenId_")},UFa=function(a){g.Ba("yt.mdx.remote.currentScreenId_",a,void 0)},VFa=function(){return g.w("yt.mdx.remote.connectData_")},n8=function(a){g.Ba("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.w("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||UFa("");g.Ba("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.E)(i8,function(b){b(a)}),i8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},o8=function(){var a=g.JH();
if(!a)return null;var b=j8().Je();return k6(b,a)},u8=function(a,b){q8()&&q8();
UFa(a.id);var c=new $7(h8,a,p8());c.connect(b,VFa());c.subscribe("beforeDisconnect",function(a){c6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},PFa=function(){var a=o8();
a?(l8("Resume connection to: "+g6(a)),u8(a,0)):(p6(),tFa(),l8("Skipping connecting because no session screen found."))},MFa=function(){var a=p8();
if(g.hc(a)){a=n6();var b=g.HH("yt-remote-session-name")||"",c=g.HH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ba("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},OFa=function(a){a?(g.GH("yt-remote-session-app",a.app),g.GH("yt-remote-session-name",a.name)):(g.IH("yt-remote-session-app"),g.IH("yt-remote-session-name"));
g.Ba("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.L.call(this);
this.D=a;this.A=b;this.B=new g.hG(this);g.M(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.ET);this.B.R(b,"captionschanged",this.mS);this.B.R(b,"captionssettingschanged",this.bH);this.B.R(b,"videoplayerreset",this.fr);this.B.R(b,"mdxautoplaycancel",this.NK);this.V=this.B.R(b,"onVolumeChange",this.fF);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.vF,this);c.subscribe("remotePlayerChange",this.Tn,this);c.subscribe("remoteQueueChange",this.fr,this);c.subscribe("autoplayUpNext",this.RE,
this);c.subscribe("previousNextChange",this.sF,this);c.subscribe("nowAutoplaying",this.kF,this);c.subscribe("autoplayDismissed",this.QE,this);this.suggestion=null;this.J=new g.mQ(64);this.C=new g.V(this.YG,500,this);g.M(this,this.C);this.F=new g.V(this.ZG,1E3,this);g.M(this,this.F);this.L=new x6(this.IX,0,this);g.M(this,this.L);this.G={};this.M=new g.V(this.yH,1E3,this);g.M(this,this.M);this.K=new g.Fl(this.pQ,1E3,this);g.M(this,this.K);this.O=g.y;this.bH();this.fr();this.Tn()},z8=function(a,b){a.D.Te(b,
a.A.getVideoData().lengthSeconds)},WFa=function(a){z8(a,0);
a.C.stop();A8(a,new g.mQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.gh()},g.pc(c,b));a.o.MG(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.yg();
if(c){var d=c.Ie();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.wk;f=EDa(f);var n=U7(c);l=l||0;var p={videoId:k,currentIndex:l};Q7(n,k,l);g.ya(b)&&(O7(n,b),p.currentTime=b);g.ya(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Og(f));Y7(c,"setPlaylist",p);e||W7(c,n);A8(a,new g.mQ(1))},XFa=function(a,b){if(b){var c=a.A.lc("captions","tracklist",{d6:1});
c&&c.length?(a.A.fd("captions","track",b),a.H=!1):(a.A.Nk("captions"),a.H=!0)}else a.A.fd("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.sQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.FU(a.A,d);a.J=b;YFa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.isa()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.xV(this,250);g.M(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);ZFa(this,g.BU(a))},ZFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.lc("remote","currentReceiver").name};
c=g.X(b,128)?g.pV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.pV("Playing on $RECEIVER_NAME",c):g.pV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.OW.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.$U.call(this,a);
this.A={key:i6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.En=new g.mQ(64);this.J=0;this.H=-1;if(!g.cN(g.Z(this.player))){a=this.player;var b=g.bQ(a);b&&(b=b.Gn())&&(b=new F8(a,b),g.M(this,b));b=new E8(a);g.M(this,b);g.RU(a,b.element,4)}},YFa=function(a,b,c){a.En=c;
a.player.U("presentingplayerstatechange",new g.xQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.yg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ia(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.wk,index:Math.max(a.player.BD(),0),currentTime:0==f?void 0:f};(d=EDa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?(n8(d||null),I7()?F7().setLaunchParams(d||
null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?c6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().Je(),(d=k6(d,b.key))&&u8(d,1))}},nEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},$Fa={},LDa={DZ:"atp",j4:"ska",B3:"que",N2:"mus",f4:"sus",Q0:"dsp"};
d6.prototype.Bh=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var q6,m6="",u6=r6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",fEa=r6("loadCastFramework")||r6("loadCastApplicationFramework"),pFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.L);g.h=x6.prototype;g.h.LL=function(a){this.C=arguments;this.o=!1;this.Ha?this.B=(0,g.I)()+this.Pd:this.Ha=g.Jg(this.D,this.Pd)};
g.h.stop=function(){this.Ha&&(g.Kg(this.Ha),this.Ha=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();x6.fa.X.call(this)};
g.h.ML=function(){this.B?(this.Ha=g.Jg(this.D,this.B-(0,g.I)()),this.B=null):(this.Ha=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Zi=null;g.h.Uf=!1;g.h.Fl=null;g.h.Iy=null;g.h.jl=null;g.h.kk=null;g.h.Oh=null;g.h.si=null;g.h.zj=null;g.h.Zc=null;g.h.qo=0;g.h.Vf=null;g.h.ys=null;g.h.Ph=null;g.h.Om=-1;g.h.uG=!0;g.h.Ji=!1;g.h.Gu=0;g.h.wr=null;var lEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.IW=function(a){a=a.target;var b=this.wr;b&&3==g.Rx(a)?b.Km():this.GH(a)};
g.h.GH=function(a){try{if(a==this.Zc)a:{var b=g.Rx(this.Zc),c=this.Zc.A,d=this.Zc.getStatus();if(g.Sd&&!g.Dc(10)||g.Ud&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yf&&!g.Vx(this.Zc))break a;this.Ji||4!=b||7==c||(8==c||0>=d?this.o.Nf(3):this.o.Nf(2));J6(this);var e=this.Zc.getStatus();this.Om=e;var f=g.Vx(this.Zc);(this.Uf=200==e)?(4==b&&F6(this),this.D?(mEa(this,b,f),g.yf&&this.Uf&&3==b&&(this.Y.W(this.A,"tick",this.EW),this.A.start())):E6(this,f),this.Uf&&!this.Ji&&(4==b?this.o.ar(this):
(this.Uf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ph=3,D6(13)):(this.Ph=0,D6(14)),F6(this),G6(this))}}catch(k){this.Zc&&g.Vx(this.Zc)}finally{}};
g.h.EW=function(){var a=g.Rx(this.Zc),b=g.Vx(this.Zc);this.qo<b.length&&(J6(this),mEa(this,a,b),this.Uf&&4!=a&&B6(this))};
g.h.QV=function(a){I6((0,g.A)(this.PV,this,a),0)};
g.h.PV=function(a){this.Ji||(J6(this),E6(this,a),B6(this))};
g.h.DF=function(a){I6((0,g.A)(this.OV,this,a),0)};
g.h.OV=function(a){this.Ji||(F6(this),this.Uf=a,this.o.ar(this),this.o.Nf(4))};
g.h.cancel=function(){this.Ji=!0;F6(this)};
g.h.fW=function(){this.Fl=null;var a=(0,g.I)();0<=a-this.Iy?(2!=this.kk&&this.o.Nf(3),F6(this),this.Ph=2,D6(18),G6(this)):pEa(this,this.Iy-a)};g.h=sEa.prototype;g.h.Eu=null;g.h.Pe=null;g.h.xr=!1;g.h.dC=null;g.h.yp=null;g.h.Mv=null;g.h.Fu=null;g.h.pf=null;g.h.Yg=-1;g.h.Nm=null;g.h.Vl=null;g.h.connect=function(a){this.Fu=a;a=L6(this.o,null,this.Fu);D6(3);this.dC=(0,g.I)();var b=this.o.H;null!=b?(this.Nm=b[0],(this.Vl=b[1])?(this.pf=1,tEa(this)):(this.pf=2,N6(this))):(b6(a,"MODE","init"),this.Pe=new z6(this,void 0,void 0,void 0),this.Pe.Zi=this.Eu,A6(this.Pe,a,!1,null,!0),this.pf=0)};
g.h.OK=function(a){if(a)this.pf=2,N6(this);else{D6(4);var b=this.o;b.ig=b.Ah.Yg;U6(b,9)}a&&this.Nf(2)};
g.h.Zt=function(a){return this.o.Zt(a)};
g.h.abort=function(){this.Pe&&(this.Pe.cancel(),this.Pe=null);this.Yg=-1};
g.h.cC=function(){return!1};
g.h.wF=function(a,b){this.Yg=a.Om;if(0==this.pf)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.ig=this.Yg;U6(c,2);return}this.Nm=c[0];this.Vl=c[1]}else c=this.o,c.ig=this.Yg,U6(c,2);else if(2==this.pf)if(this.xr)D6(7),this.Mv=(0,g.I)();else if("11111"==b){if(D6(6),this.xr=!0,this.yp=(0,g.I)(),c=this.yp-this.dC,!g.Sd||g.Dc(10)||500>c)this.Yg=200,this.Pe.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.yp=this.Mv=(0,g.I)(),this.xr=!1};
g.h.ar=function(){this.Yg=this.Pe.Om;if(this.Pe.Uf)0==this.pf?this.Vl?(this.pf=1,tEa(this)):(this.pf=2,N6(this)):2==this.pf&&((!g.Sd||g.Dc(10)?!this.xr:200>this.Mv-this.yp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.pf?D6(9):2==this.pf&&D6(10);var a=this.o;a.ig=this.Yg;U6(a,2)}};
g.h.ho=function(){return this.o.ho()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Nf=function(a){this.o.Nf(a)};g.h=O6.prototype;g.h.qm=null;g.h.se=null;g.h.Ec=null;g.h.Du=null;g.h.Ap=null;g.h.wA=null;g.h.Np=null;g.h.Nn=0;g.h.ER=0;g.h.Od=null;g.h.Ih=null;g.h.Mg=null;g.h.Oi=null;g.h.Ah=null;g.h.us=null;g.h.Fk=-1;g.h.QC=-1;g.h.ig=-1;g.h.ck=0;g.h.Tj=0;g.h.Mi=8;var V6=new g.Yf;g.B(vEa,g.wf);g.B(wEa,g.wf);g.B(xEa,g.wf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Du=b;this.qm=c||{};d&&g.ya(e)&&(this.qm.OSID=d,this.qm.OAID=e);this.F?(I6((0,g.A)(this.PA,this,a),100),BEa(this)):this.PA(a)};
g.h.PA=function(a){this.Ah=new sEa(this);this.Ah.Eu=null;this.Ah.A=this.D;this.Ah.connect(a)};
g.h.cC=function(){return 0==this.o};
g.h.CF=function(a){this.Ih=null;EEa(this,a)};
g.h.BF=function(){this.Mg=null;this.Ec=new z6(this,this.B,"rpc",this.G);this.Ec.Zi=null;this.Ec.Gu=0;var a=this.wA.clone();g.mn(a,"RID","rpc");g.mn(a,"SID",this.B);g.mn(a,"CI",this.us?"0":"1");g.mn(a,"AID",this.Fk);P6(this,a);if(!g.Sd||g.Dc(10))g.mn(a,"TYPE","xmlhttp"),A6(this.Ec,a,!0,this.Np,!1);else{g.mn(a,"TYPE","html");var b=this.Ec,c=!!this.Np;b.kk=3;b.Oh=a6(a.clone());oEa(b,c)}};
g.h.wF=function(a,b){if(0!=this.o&&(this.Ec==a||this.se==a))if(this.ig=a.Om,this.se==a&&3==this.o)if(7<this.Mi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ea(c)&&3==c.length)if(0==c[0])a:{if(!this.Mg){if(this.Ec)if(this.Ec.jl+3E3<this.se.jl)R6(this),this.Ec.cancel(),this.Ec=null;else break a;T6(this);D6(19)}}else this.QC=c[1],0<this.QC-this.Fk&&37500>c[2]&&this.us&&0==this.Tj&&!this.Oi&&(this.Oi=I6((0,g.A)(this.hS,this),6E3));else U6(this,11)}else b!=$Fa.G_.o&&U6(this,11);else if(this.Ec==a&&
R6(this),!g.F(b)){c=this.D.parse(b);g.Ea(c);for(var d=0;d<c.length;d++){var e=c[d];this.Fk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Np=e[2],e=e[3],null!=e?this.Mi=e:this.Mi=6,this.o=3,this.Od&&this.Od.JA(),this.wA=L6(this,this.ho()?this.Np:null,this.Du),FEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Od&&this.Od.IA(e),this.Tj=0)}}};
g.h.hS=function(){null!=this.Oi&&(this.Oi=null,this.Ec.cancel(),this.Ec=null,T6(this),D6(20))};
g.h.ar=function(a){if(this.Ec==a){R6(this);this.Ec=null;var b=2}else if(this.se==a)this.se=null,b=1;else return;this.ig=a.Om;if(0!=this.o)if(a.Uf)1==b?(b=(0,g.I)()-a.jl,V6.dispatchEvent(new wEa(V6,a.zj?a.zj.length:0,b,this.ck)),Q6(this),this.C.length=0):FEa(this);else{var c=a.Ph,d;if(!(d=3==c||7==c||0==c&&0<this.ig)){if(d=1==b)this.se||this.Ih||1==this.o||2<=this.ck?d=!1:(this.Ih=I6((0,g.A)(this.CF,this,a),GEa(this,this.ck)),this.ck++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,5);
break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.kL=function(a){if(!g.C(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.yX=function(a){a?D6(2):(D6(1),HEa(this,8))};
g.h.Zt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Lx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Od&&this.Od.isActive(this)};
g.h.Nf=function(a){V6.dispatchEvent(new xEa(V6,a))};
g.h.ho=function(){return!(!g.Sd||g.Dc(10))};
g.h=IEa.prototype;g.h.JA=function(){};
g.h.IA=function(){};
g.h.HA=function(){};
g.h.Lt=function(){};
g.h.IB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.L);g.h=W6.prototype;g.h.GV=function(){this.Pd=Math.min(3E5,2*this.Pd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Pd+15E3*Math.random();g.Lu(this.o,a);this.A=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Pd=5E3};g.B(X6,IEa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Lk=function(a){return this.B.aj(a)};
g.h.U=function(a,b){return this.B.U.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.uf(this.B),LEa(this),g.uf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Od=null);d.Od=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Fk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.pc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&CEa(this.o,c)};
g.h.JA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)CEa(this.o,a[b])}this.U("handlerOpened")};
g.h.HA=function(a){var b=2==a&&401==this.o.ig;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.Lt=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.IB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.pc(a,this.D);return a};
g.h.IA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),AEa(this.o)):this.U("handlerMessage",new JEa(a[0],a[1]))};
g.h.bY=function(){this.A.isActive();var a=this.o,b=0;a.Ec&&b++;a.se&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var TEa=(0,g.I)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.kG);g7.prototype.Je=function(){return this.o};
g7.prototype.contains=function(a){return!!j6(this.o,a)};
g7.prototype.get=function(a){return a?k6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.kG);var aGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ha)&&this.KH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ha)||(g.EE(this.Ha),this.Ha=window.NaN)};
g.h.X=function(){this.stop();h7.fa.X.call(this)};
g.h.KH=function(){this.Ha=window.NaN;this.o=g.TE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.dY,this),onError:(0,g.A)(this.cY,this),Td:(0,g.A)(this.eY,this)})};
g.h.dY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.U("pairingComplete",new e6(c))};
g.h.cY=function(a){this.o=null;a.status&&404==a.status?this.A>=aGa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=aGa[this.A],this.Ha=g.CE((0,g.A)(this.KH,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.eY=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.HH("yt-remote-lounge-token-expiration")&&XEa(this);g.EE(this.A);this.A=g.CE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);UEa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||XEa(this)};
g.h.remove=function(a,b){var c=i7(this);WEa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.os=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.X=function(){g.EE(this.A);j7.fa.X.call(this)};
g.h.aM=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.ZL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.kG);g.h=m7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.HH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.I)()-144E5<a?0:a)?o7(this):(this.C=(0,g.I)()+3E5,g.GH("yt-remote-fast-check-period",this.C),this.Fx())};
g.h.isEmpty=function(){return g.hc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Sb(this.o,function(b,d){return b&&!!k6(a,d)},this);
n7(this,b)};
g.h.X=function(){g.EE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);m7.fa.X.call(this)};
g.h.Fx=function(){g.EE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=$Ea(this);if(g.Wb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.bc(a).join(",")},(0,g.A)(this.oV,this,a),(0,g.A)(this.nV,this))}else n7(this,{}),o7(this)};
g.h.oV=function(a,b){this.A=null;var c=g.bc($Ea(this));if(g.pb(c,g.bc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.xc("Changing Screen set during request."),this.Fx()};
g.h.nV=function(a){this.xc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.xc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.os=function(a,b,c,d){this.B.contains(a)?this.B.os(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.Je=function(a){return a?this.o:g.bb(this.o,(0,g.fe)(this.C,function(a){return!this.contains(a)},this))};
g.h.LH=function(){return(0,g.fe)(this.Je(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.MH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.uf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.uf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.gY=function(a,b,c,d){g.TE($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new e6(d.screen||{});if(!e.name||dFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);dFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Td:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.uf(this.B);g.uf(this.A);p7.fa.X.call(this)};
g.h.nM=function(){eFa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.kG);g.h=s7.prototype;g.h.dr=function(a){this.B=a;this.U("sessionScreen",this.B)};
g.h.Oe=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.OH=function(){return null};
g.h.Qx=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Qx("");s7.fa.X.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.Px=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);gFa(this)};
g.h.Hk=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Oe()},this),(0,g.A)(function(){this.Oe(Error("Failed to stop receiver app."))},this)):this.Oe(Error("Stopping cast device witout session."))};
g.h.Qx=g.y;g.h.X=function(){this.info("disposeInternal");g.EE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.fa.X.call(this)};
g.h.rW=function(a,b){if(!this.la())if(b){var c=g.Gx(b);if(g.Ha(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":fFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.SB=function(a,b,c,d){cFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.CE((0,g.A)(this.SB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.OH=function(){return this.o};
g.h.hY=function(a){this.la()||a||(t7(this,"Cast session died."),this.Oe())};g.B(v7,s7);g.h=v7.prototype;g.h.Px=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Hk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.y;g.EE(this.F);this.C?this.C.stop((0,g.A)(this.Oe,this,null),(0,g.A)(this.Oe,this,"Failed to stop DIAL device.")):this.Oe()};
g.h.X=function(){this.o();this.o=g.y;g.EE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.fa.X.call(this)};
g.h.kY=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.y,this.Oe())};
g.h.kv=function(a){this.K=i6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,iFa(this));a(b);hFa(this)}else this.G=(0,g.A)(function(){g.EE(this.F);this.G=g.y;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,iFa(this));a(b);hFa(this)},this),this.F=g.CE((0,g.A)(function(){this.G()},this),100)};
g.h.xN=function(a,b,c){cFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.dr(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.kv(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.kv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Oe()};
w7.prototype.Px=g.y;w7.prototype.Hk=function(){g.EE(this.o);this.o=window.NaN;var a=k6(this.J.Je(),this.A.label);a?this.dr(a):this.Oe(Error("No such screen"))};
w7.prototype.X=function(){g.EE(this.o);this.o=window.NaN;w7.fa.X.call(this)};g.B(x7,g.kG);g.h=x7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.yF,this),(0,g.A)(this.WU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.PS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),QEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.NH,this)),this.B=kFa(this),window.chrome.cast.setCustomReceivers(this.B,g.y,(0,g.A)(function(a){this.xc("Failed to set initial custom receivers: "+g.Og(a))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.xc("Failed to initialize API: "+g.Og(a));
b(!1)},this))};
g.h.hX=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=k6(this.A.Je(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=jFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.y,(0,g.A)(function(a){this.xc("Failed to set initial custom receivers: "+g.Og(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Qx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.iX=function(a){this.la()?this.xc("Setting connection data on disposed cast v2"):this.o?this.o.Hk(a):this.xc("Setting connection data without a session")};
g.h.jY=function(){this.la()?this.xc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.yF,this),(0,g.A)(this.sV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.NH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Za(g.w("yt.mdx.remote.debug.handlers_")||[],NEa);g.uf(this.o);x7.fa.X.call(this)};
g.h.xc=function(a){c7("Controller",a)};
g.h.zF=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.SU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.U("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.xc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.xc("Stopping receiver w/o session: "+a.friendlyName)}else this.xc("onReceiverAction_ called without receiver.")};
g.h.PS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.xc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.xc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.xc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.xN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.kv,b))};
g.h.yF=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.xc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=k6(this.A.Je(),c.label);
d&&f6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.uf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.zF,this,this.o)),this.o.Hk(null));this.o.Px(a)}}};
g.h.iY=function(){return this.o?this.o.OH():null};
g.h.sV=function(a){this.la()||(this.xc("Failed to estabilish a session: "+g.Og(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.WU=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.NH=function(){this.la()||(this.B=kFa(this),y7("Updating custom receivers: "+g.Og(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.y,(0,g.A)(function(){this.xc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.iX;x7.prototype.setConnectedScreenStatus=x7.prototype.hX;x7.prototype.stopSession=x7.prototype.jY;x7.prototype.getCastSession=x7.prototype.iY;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.mg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.kG);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.y,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.y,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.JH=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.tb()||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.y,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.La(this.JH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.y,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.xc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.xc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.MG=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Og(b.style),g.pc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.MG,a,b))};
g.h.az=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=U7(this);c.audioTrackId=b.Pb.id;W7(this,c)}else V7(this,g.La(this.az,a,b))};
g.h.kr=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.kr,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.jB=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.jB)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.fa.dispose.call(this)};
g.h.X=function(){xFa(this);this.C=null;this.D.clear();S7(this,null);T7.fa.X.call(this)};
g.h.bz=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.ZC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.NU=function(a,b){this.U(a,b)};
g.h.oS=function(a){if(!a)this.Qn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.Qn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),yFa(this),this.U("remotePlayerChange")};
g.h.nS=function(a){a?(yFa(this),this.U("remotePlayerChange")):this.Qn(null)};
g.h.gy=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.AS=function(){var a=uFa();a&&S7(this,a)};
g.h.xc=function(a){c7("CP",a)};g.B($7,g.kG);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.ya(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.ya(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Og(l));this.o.connect({method:"setPlaylist",
params:g.Og(l)},a,TDa())}else a8("Connecting without params"),this.o.connect({},a,TDa());AFa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.fa.dispose.call(this)};
g.h.X=function(){c8(this);e8(this);d8(this);g.EE(this.J);this.J=window.NaN;g.EE(this.K);this.K=window.NaN;this.B=null;g.VF(this.V);this.V.length=0;this.o.dispose();$7.fa.X.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.QL=function(){this.F(2)};
g.h.sS=function(){a8("Channel opened");this.O&&(this.O=!1,d8(this),this.M=g.CE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
XDa(KEa(this.o),this.ba)};
g.h.pS=function(){a8("Channel closed");(0,window.isNaN)(this.D)?p6(!0):p6();this.dispose()};
g.h.qS=function(a){p6();(0,window.isNaN)(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.rS=function(a){a.params?a8("Received: action="+a.action+", params="+g.Og(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Gx(a.params.devices);this.A=(0,g.J)(a,function(a){return new d6(a)});
a=!!g.Ra(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
DFa(this,a);break;case "loungeScreenDisconnected":g.$a(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
DFa(this,!1);break;case "remoteConnected":var b=new d6(g.Gx(a.params.device));g.Ra(this.A,function(a){return b?a.id==b.id:!1})||g.Xa(this.A,b);
break;case "remoteDisconnected":b=new d6(g.Gx(a.params.device));g.$a(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":FFa(this,a);break;case "nowPlaying":HFa(this,a);break;case "onStateChange":GFa(this,a);break;case "onAdStateChange":IFa(this,a);break;case "onVolumeChanged":JFa(this,a);break;case "onSubtitlesTrackChanged":EFa(this,a);break;case "nowAutoplaying":KFa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.U("autoplayModeChange",this.C);"DISABLED"==this.C&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":LFa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.QW=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Lk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?Y6(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&p6();LEa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.EE(this.J),this.J=g.CE((0,g.A)(this.QW,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.Og(this.qb.o)==g.Og(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.E)(c,function(a){this.U(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Ra(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.I)():window.NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.aa=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.aa;$7.prototype.ga=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ga;$7.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.Mu(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);CFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.Je=function(a){return this.xd.$_gs(a)};
g.h.contains=function(a){return!!this.xd.$_c(a)};
g.h.get=function(a){return this.xd.$_g(a)};
g.h.start=function(){this.xd.$_st()};
g.h.add=function(a,b,c){this.xd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.xd.$_r(a,b,c)};
g.h.os=function(a,b,c,d){this.xd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.xd.$_ubk(this.A[a]);this.A.length=0;this.xd=null;g8.fa.X.call(this)};
g.h.fY=function(){this.U("screenChange")};
g.h.mU=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.gY;p7.prototype.$_gsppc=p7.prototype.MH;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.os;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.Je;p7.prototype.$_gos=p7.prototype.LH;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Lk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.L);g.h=y8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.C.stop();this.F.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.vF,this);this.o.unsubscribe("remotePlayerChange",this.Tn,this);this.o.unsubscribe("remoteQueueChange",this.fr,this);this.o.unsubscribe("autoplayUpNext",this.RE,this);this.o.unsubscribe("previousNextChange",this.sF,this);this.o.unsubscribe("nowAutoplaying",this.kF,this);this.o.unsubscribe("autoplayDismissed",this.QE,this);this.o=this.D=null};
g.h.TD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Km(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.az(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.az(this.A.getVideoData(1).videoId,c)}};
g.h.mS=function(a){this.L.LL(a)};
g.h.IX=function(a){this.TD("control_subtitles_set_track",g.hc(a)?null:a)};
g.h.bH=function(){var a=this.A.lc("captions","track");g.hc(a)||C8(this,a)};
g.h.fF=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Tn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Tn,this)}};
g.h.ET=function(){g.hc(this.G)||XFa(this,this.G);this.H=!1};
g.h.vF=function(a,b){this.F.stop();2==b&&this.ZG()};
g.h.Tn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.ol(1);break;case 1082:case 1083:this.D.ol(0);break;default:this.D.ol(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.mQ(8));this.YG();break;case 1085:case 3:A8(this,new g.mQ(9));break;case 1083:case 0:A8(this,new g.mQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.mQ(4));break;case 2:A8(this,new g.mQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.mQ(64));break;case -1E3:A8(this,new g.mQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,XFa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.yH()}else WFa(this)};
g.h.sF=function(){this.A.U("mdxpreviousnextchange")};
g.h.fr=function(){B8(this)||WFa(this)};
g.h.NK=function(){this.o.jB()};
g.h.RE=function(a){a&&(a=g.TE("/watch_queue_ajax",{method:"GET",ld:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.SV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.SV=function(a,b){var c=new g.gP(g.Z(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.kF=function(a){(0,window.isNaN)(a)||this.A.U("mdxnowautoplaying",a)};
g.h.QE=function(){this.A.U("mdxautoplaycanceled")};
g.h.pQ=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.JH(a)};
g.h.yH=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.V);a.muted?this.A.mute():this.A.zg();this.A.setVolume(a.volume);this.V=this.B.R(this.A,"onVolumeChange",this.fF)}};
g.h.YG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.mQ(8));z8(this,P7(a));this.C.start()}};
g.h.ZG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){ZFa(this,a.state)};g.r(F8,g.OW);F8.prototype.L=function(){var a=this.B.lc("remote","receivers");a&&1<a.length&&!this.B.lc("remote","quickCast")?(this.J=g.rb(a,this.F,this),g.PW(this,(0,g.J)(a,this.F)),a=this.B.lc("remote","currentReceiver"),this.Mf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.Lf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
F8.prototype.Rd=function(a){g.OW.prototype.Rd.call(this,a);this.B.fd("remote","currentReceiver",this.J[a]);this.D.Sb()};g.r(G8,g.$U);g.h=G8.prototype;g.h.create=function(){QFa(g.UM(g.Z(this.player)));this.D.push(g.xG("yt-remote-before-disconnect",this.iS,this));this.D.push(g.xG("yt-remote-connection-change",this.XU,this));this.D.push(g.xG("yt-remote-receiver-availability-change",this.tF,this));this.D.push(g.xG("yt-remote-auto-connect",this.VU,this));this.D.push(g.xG("yt-remote-receiver-resumed",this.UU,this));this.tF()};
g.h.load=function(){this.player.iw();g.$U.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=VFa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Te(a);YFa(this,this.En,this.En);g.s0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.B=this.A;g.vf(this.C,this.o);this.o=this.C=null;g.$U.prototype.unload.call(this);g.s0(this.player.app,5)};
g.h.X=function(){g.yG(this.D);g.$U.prototype.X.call(this)};
g.h.mi=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.TD.apply(this.C,[a].concat(g.ea(c)))};
g.h.ol=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.GL=function(){return this.loaded?this.C.suggestion:null};
g.h.mg=function(){return this.o?U7(this.o).mg:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Te=function(a,b){this.J=a||0;this.player.U("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Z(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Rc():!a.isAdPlaying()&&this.player.Rc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+
N7(a):a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.kr=function(){this.o&&this.o.kr()};
g.h.iS=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.XU=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.uf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.AD(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.tF=function(){this.F=[this.A].concat(SFa());var a=s8()||this.A;H8(this,a);this.player.Aa("onMdxReceiversChange")};
g.h.VU=function(){var a=s8();H8(this,a)};
g.h.UU=function(){this.B=s8()};
g.h.Oc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.gy=function(){this.o.gy()};
g.h.zc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.JZ.remote=G8;})(_yt_player);
